name: Approve PR

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number'
        required: true

jobs:
  approve_pr:
    environment: pull-request
    runs-on: ubuntu-latest

    steps:
      - name: Get PR info
        id: pr_info
        run: |
          PR_AUTHOR=$(gh pr view ${{ github.event.inputs.pr_number }} --repo flathub/net.devolutions.RDM --json author -q '.author.login')
          echo "::set-output name=author::$PR_AUTHOR"

      - name: Validate Actor
        run: |
          if [ "${{ steps.pr_info.outputs.author }}" == "${{ github.actor }}" ]; then
            echo "::error:: You can't approve your own PR"
            exit 1
          fi

      - name: Merge pull request
        run: |
          Write-Host "Waiting for checks to start..."
          Start-Sleep -Seconds 120
          Write-Host "Checking if checks have started..."
          gh pr checks --watch --fail-fast
          gh pr merge --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.DEVOLUTIONSBOT_WRITE_TOKEN }}
